---
apiVersion: v2
name: event-platform
description: Umbrella chart for the complete Event Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: event-api
    version: ~0.1.0
    repository: file://../event-api
  - name: event-ui
    version: ~0.1.0
    repository: file://../event-ui
