---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: event-ejsadiarin-com-cert
  namespace: default
spec:
  secretName: event-ejsadiarin-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - event.ejsadiarin.com
