---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: cm9vdA== # "root" - Use a more secure password in production and encode it with base64
  connection-string: cm9vdDpyb290QG15c3FsOjMzMDYvbGVhcF9kYg== # "root:root@mysql:3306/leap_db"
