apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-api.fullname" . }}-config
  labels:
    {{- include "event-api.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
