{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "event-api.fullname" . }}-mysql
  labels:
    {{- include "event-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "event-api.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      {{- include "event-api.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "event-api.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: mysql
          image: {{ .Values.database.image }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "event-api.fullname" . }}-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.configMap.MYSQL_DATABASE }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  {{- if .Values.database.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.database.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-api.fullname" . }}-mysql
  labels:
    {{- include "event-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "event-api.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
